### ISSUE TITLE
Internal Server Error /captcha 

### ISSUE THREAD

**Issue by duy13** [kyprizel/testcookie-recaptcha-processor#1]
1. Build nginx with testcookie-nginx-module
2. pip install -r requirements.txt
3. sh start.sh
   Listening at: http://127.0.0.1:10101
4. Use Example configuration:

```
`    testcookie_refresh_template "<html><body><script type=\"text/javascript\">var olC=function(){grecaptcha.render('captcha',{'sitekey':'recaptcha_public_key','callback':setcookie});};var setcookie=function(resp){document.getElementById('cpt').submit();};</script><script src=\"https://www.google.com/recaptcha/api.js?onload=olC&render=explicit\" async defer></script><form method=post action=\"/captcha\" id=\"cpt\"><div id=\"captcha\"></div></form></body></html>";`
```
1. Replace "`recaptcha_public_key`" by Sitekey from https://www.google.com/recaptcha/admin#list
2. Goto web and it show recaptcha
3. Pass recaptcha, it will redirect to => http://domain/captcha (status 500)

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Centos 7 Nginx 1.10.1

**Comment by duy13** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/testcookie-recaptcha-processor-master/app.py", line 39, in handler
    secret = settings.RE_SECRETS.get(domaiin)
NameError: global name 'domaiin' is not defined
```

**Comment by kyprizel** [comment]
fixed in https://github.com/kyprizel/testcookie-recaptcha-processor/commit/694e30aad8a9b02c0977523e55d6c323f1253e10

**Comment by duy13** [comment]
Helo! As i see:

```
@app.route('/', methods=['POST'])
def handler():
    domain = request.headers.get('Testcookie-Domain', '')
    nexturl = request.headers.get('Testcookie-Nexturl', '/')   #### <==
    cookie_name = request.headers.get('Testcookie-Name')
    cookie_val = request.headers.get('Testcookie-Value')
-    secret = settings.RE_SECRETS.get(domaiin)
+   secret = settings.RE_SECRETS.get(domain)
    if not cookie_name or not cookie_val or not secret:
        abort(500)
    ip = get_client_addr()
    if check_recaptcha(secret, request.form['g-recaptcha-response'], ip):
        resp = redirect(nexturl)
        resp.set_cookie(cookie_name, cookie_val)
        return resp
    return redirect(nexturl)
```

If `nexturl = request.headers.get('Testcookie-Nexturl', '/')`  => Browser Client after pass recaptcha and testcookie-recaptcha-processor it will be redirect to => '/' (http://domain.com/) it does not use `$testcookie_nexturl` or `$request_uri` (like http://domain.com/abcdef)

```
    location = /captcha {
                testcookie var;
        proxy_set_header Host             $host;
        proxy_set_header X-Real-IP        $remote_addr;
        proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header Testcookie-Domain "domain.com";
        proxy_set_header Testcookie-Value $testcookie_set;
        proxy_set_header Testcookie-Nexturl $testcookie_nexturl;
        proxy_set_header Testcookie-Name "BPC";
        proxy_pass http://127.0.0.1:10101/;

    }
```

**Comment by kyprizel** [comment]
Please, see how Python dict get works.

**Comment by duy13** [comment]
Thanks! I think app.py alright so i change 
`proxy_set_header Testcookie-Nexturl $testcookie_nexturl;`
to 
`proxy_set_header Testcookie-Nexturl "/something-404";`
It work, after pass recaptcha and testcookie-recaptcha-processor Client will be redirect to => '/something-404', so  I think app.py alright.
But if use
`proxy_set_header Testcookie-Nexturl $testcookie_nexturl;`

Client will be redirect to => '/' ; i think $testcookie_nexturl does not work, how i can check variable of $testcookie_nexturl ?. Thanks!

**Comment by duy13** [comment]
Ok, i have a solution,  $testcookie_nexturl change to $http_referer
`proxy_set_header Testcookie-Nexturl $http_referer;`

As i see: variable of $testcookie_nexturl only work in testcookie_refresh_template, when you call it on http{}, server{}, location{}... $testcookie_nexturl does not work.
